{
 "title": "Go Demo App Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memstats Alloc Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"demo-app:2221\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Login Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "total_login_request{instance=\"demo-app:2221\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Register Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "total_register_request{instance=\"demo-app:2221\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"demo-app:2221\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}