server:
  http_listen_port: 9080
  grpc_listen_port: 9081

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
- job_name: system
  static_configs:
    - targets:
      - localhost
      labels:
        job: varlog
        __path__: /var/log/*.log