{
 "title": "Demo App Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Go Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_threads{instance=\"demo-app:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Routines Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"demo-app:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Register Sucess",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_success_register{instance=\"demo-app:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Success Login",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_success_login{instance=\"demo-app:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Register",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_failed_register{instance=\"demo-app:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Login",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_failed_login{job=\"prometheus-demo-app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}